# Generated by Django 2.0 on 2020-06-01 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[['Fi fy Hunan', 'Fi fy Hunan'], ['Gwyliau', 'Gwyliau'], ['Ysgol', 'Ysgol'], ['Tywydd', 'Tywydd'], ['Amser', 'Amser'], ['Bwyd', 'Bwyd'], ['Ffasiwn', 'Ffasiwn'], ['Teulu a Ffrindiau', 'Teulu a Ffrindiau'], ['Trefn Ddyddiol', 'Trefn Ddyddiol'], ['Anifeiliad Anwes', 'Anifeiliad Anwes'], ['Cartref', 'Cartref'], ['Ardal', 'Ardal'], ['Hamdden a Hobiau', 'Hamdden a Hobiau'], ['Chwaraeon', 'Chwaraeon'], ['Digwyddiadau Arbennig', 'Digwyddiadau Arbennig'], ['Amser Gorffenol', 'Amser Gorffenol'], ['Cerddioraeth', 'Cerddioraeth'], ['Cymru, Digwylliant ac Enwogion', 'Cymru, Digwylliant ac Enwogion'], ["Cadw'n Iach", "Cadw'n Iach"], ['Y Penwythnos', 'Y Penwythnos'], ['Amser Dyfodol', 'Amser Dyfodol'], ['Gwaith', 'Gwaith'], ['Problemau Pobl Ifanc', 'Problemau Pobl Ifanc'], ['Y Amgylchedd', 'Y Amgylchedd'], ['Cyfryngau', 'Cyfryngau'], ['Technoleg', 'Technoleg']], max_length=50)),
                ('lesson_no', models.IntegerField()),
                ('phrase', models.CharField(default='', max_length=150)),
                ('translated_phrase', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='LessonStart',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_phrase', models.CharField(default='', max_length=150)),
                ('current_translated_phrase', models.CharField(default='', max_length=150)),
                ('status', models.CharField(default='learning', max_length=10)),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(choices=[['Fi fy Hunan', 'Fi fy Hunan'], ['Gwyliau', 'Gwyliau'], ['Ysgol', 'Ysgol'], ['Tywydd', 'Tywydd'], ['Amser', 'Amser'], ['Bwyd', 'Bwyd'], ['Ffasiwn', 'Ffasiwn'], ['Teulu a Ffrindiau', 'Teulu a Ffrindiau'], ['Trefn Ddyddiol', 'Trefn Ddyddiol'], ['Anifeiliad Anwes', 'Anifeiliad Anwes'], ['Cartref', 'Cartref'], ['Ardal', 'Ardal'], ['Hamdden a Hobiau', 'Hamdden a Hobiau'], ['Chwaraeon', 'Chwaraeon'], ['Digwyddiadau Arbennig', 'Digwyddiadau Arbennig'], ['Amser Gorffenol', 'Amser Gorffenol'], ['Cerddioraeth', 'Cerddioraeth'], ['Cymru, Digwylliant ac Enwogion', 'Cymru, Digwylliant ac Enwogion'], ["Cadw'n Iach", "Cadw'n Iach"], ['Y Penwythnos', 'Y Penwythnos'], ['Amser Dyfodol', 'Amser Dyfodol'], ['Gwaith', 'Gwaith'], ['Problemau Pobl Ifanc', 'Problemau Pobl Ifanc'], ['Y Amgylchedd', 'Y Amgylchedd'], ['Cyfryngau', 'Cyfryngau'], ['Technoleg', 'Technoleg']], max_length=50)),
                ('question_1', models.CharField(default='', max_length=100)),
                ('answer_1', models.TextField(default='', max_length=100)),
                ('question_2', models.CharField(default='', max_length=100)),
                ('answer_2', models.TextField(default='', max_length=100)),
                ('question_3', models.CharField(default='', max_length=100)),
                ('answer_3', models.TextField(default='', max_length=100)),
                ('question_4', models.CharField(default='', max_length=100)),
                ('answer_4', models.TextField(default='', max_length=100)),
                ('question_5', models.CharField(default='', max_length=100)),
                ('answer_5', models.TextField(default='', max_length=100)),
                ('question_6', models.CharField(default='', max_length=100)),
                ('answer_6', models.TextField(default='', max_length=100)),
                ('question_7', models.CharField(default='', max_length=100)),
                ('answer_7', models.TextField(default='', max_length=100)),
                ('question_8', models.CharField(default='', max_length=100)),
                ('answer_8', models.TextField(default='', max_length=100)),
                ('question_9', models.CharField(default='', max_length=100)),
                ('answer_9', models.TextField(default='', max_length=100)),
                ('question_10', models.CharField(default='', max_length=100)),
                ('answer_10', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
