# Generated by Django 2.0 on 2020-05-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welsh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welsh_text', models.CharField(max_length=100)),
                ('english_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='lessonanswer',
            name='phrase',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='question',
        ),
        migrations.DeleteModel(
            name='LessonAnswer',
        ),
        migrations.DeleteModel(
            name='LessonPhrase',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
    ]
