# Generated by Django 2.0 on 2020-05-26 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('welsh', '0002_auto_20200514_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(choices=[['Fi fy Hunan', 'Fi fy Hunan'], ['Gwyliau', 'Gwyliau'], ['Ysgol', 'Ysgol'], ['Tywydd', 'Tywydd'], ['Amser', 'Amser'], ['Bwyd', 'Bwyd'], ['Ffasiwn', 'Ffasiwn'], ['Teulu a Ffrindiau', 'Teulu a Ffrindiau'], ['Trefn Ddyddiol', 'Trefn Ddyddiol'], ['Anifeiliad Anwes', 'Anifeiliad Anwes'], ['Cartref', 'Cartref'], ['Cysyllteiriau ac Idiomau', 'Cysyllteiriau ac Idiomau'], ['Hamdden a Hobiau', 'Hamdden a Hobiau'], ['Chwaraeon', 'Chwaraeon'], ['Digwyddiadau Arbennig', 'Digwyddiadau Arbennig'], ['Amser Gorffenol', 'Amser Gorffenol'], ['Cerddioraeth', 'Cerddioraeth'], ['Cymru, Digwylliant ac Enwogion', 'Cymru, Digwylliant ac Enwogion'], ["Cadw'n Iach", "Cadw'n Iach"], ['Y Penwythnos', 'Y Penwythnos'], ['Amser Dyfodol', 'Amser Dyfodol'], ['Gwaith', 'Gwaith'], ['Problemau Pobl Ifanc', 'Problemau Pobl Ifanc'], ['Y Amgylchedd', 'Y Amgylchedd'], ['Cyfryngau', 'Cyfryngau'], ['Technoleg', 'Technoleg']], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestTaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welsh.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welsh.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welsh.Question')),
                ('test_taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welsh.TestTaker')),
            ],
        ),
        migrations.DeleteModel(
            name='Phrase',
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welsh.Test'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welsh.Question'),
        ),
    ]
