# Generated by Django 2.0 on 2020-05-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welsh', '0005_auto_20200526_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='answer',
            new_name='answer_1',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='question',
            new_name='question_1',
        ),
        migrations.AddField(
            model_name='test',
            name='answer_10',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='answer_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='answer_3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='answer_4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='answer_5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='answer_6',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='answer_7',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='answer_8',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='answer_9',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='question_10',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='question_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='question_3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='question_4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='question_5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='question_6',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='question_7',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='question_8',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='question_9',
            field=models.CharField(default='', max_length=50),
        ),
    ]
