# Generated by Django 2.0 on 2020-05-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welsh', '0006_auto_20200526_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answer_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_10',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_6',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_7',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_8',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_9',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_10',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_6',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_7',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_8',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_9',
            field=models.CharField(default='', max_length=100),
        ),
    ]
