# Generated by Django 2.0 on 2020-05-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welsh', '0007_auto_20200527_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answer_1',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_10',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_2',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_3',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_4',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_5',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_6',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_7',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_8',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_9',
            field=models.TextField(default='', max_length=100),
        ),
    ]
