# Generated by Django 2.0 on 2020-05-31 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('welsh', '0010_auto_20200531_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonStart',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=20)),
                ('current_phrase', models.CharField(default='', max_length=150)),
                ('current_translated_phrase', models.CharField(default='', max_length=150)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
