# Generated by Django 2.0 on 2020-05-31 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welsh', '0011_auto_20200531_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonstart',
            name='answer',
        ),
    ]
