# Generated by Django 2.0 on 2020-05-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welsh', '0012_remove_lessonstart_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstart',
            name='status',
            field=models.CharField(default='learning', max_length=10),
        ),
    ]
