# Generated by Django 2.0 on 2020-05-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welsh', '0013_lessonstart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstart',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
