# Generated by Django 2.0 on 2020-05-28 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[['Fi fy Hunan', 'Fi fy Hunan'], ['Gwyliau', 'Gwyliau'], ['Ysgol', 'Ysgol'], ['Tywydd', 'Tywydd'], ['Amser', 'Amser'], ['Bwyd', 'Bwyd'], ['Ffasiwn', 'Ffasiwn'], ['Teulu a Ffrindiau', 'Teulu a Ffrindiau'], ['Trefn Ddyddiol', 'Trefn Ddyddiol'], ['Anifeiliad Anwes', 'Anifeiliad Anwes'], ['Cartref', 'Cartref'], ['Cysyllteiriau ac Idiomau', 'Cysyllteiriau ac Idiomau'], ['Hamdden a Hobiau', 'Hamdden a Hobiau'], ['Chwaraeon', 'Chwaraeon'], ['Digwyddiadau Arbennig', 'Digwyddiadau Arbennig'], ['Amser Gorffenol', 'Amser Gorffenol'], ['Cerddioraeth', 'Cerddioraeth'], ['Cymru, Digwylliant ac Enwogion', 'Cymru, Digwylliant ac Enwogion'], ["Cadw'n Iach", "Cadw'n Iach"], ['Y Penwythnos', 'Y Penwythnos'], ['Amser Dyfodol', 'Amser Dyfodol'], ['Gwaith', 'Gwaith'], ['Problemau Pobl Ifanc', 'Problemau Pobl Ifanc'], ['Y Amgylchedd', 'Y Amgylchedd'], ['Cyfryngau', 'Cyfryngau'], ['Technoleg', 'Technoleg']], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='gamephrase',
            name='phrase_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Topic'),
        ),
    ]
