# Generated by Django 2.0 on 2020-05-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200528_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamephrase',
            name='phrase',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='gamephrase',
            name='phrase_topic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='games.Topic'),
        ),
        migrations.AlterField(
            model_name='gamephrase',
            name='translated_phrase',
            field=models.CharField(default='', max_length=50),
        ),
    ]
