# Generated by Django 2.0 on 2020-05-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200528_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='HangmanGame',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=20)),
                ('guessed', models.CharField(default='', max_length=10)),
                ('status', models.CharField(default='ongoing', max_length=10)),
            ],
        ),
    ]
