# Generated by Django 2.0 on 2020-05-28 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_hangmangame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HangmanGame',
        ),
    ]
