# Generated by Django 2.0 on 2020-05-28 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0006_hangmangame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hangmangame',
            name='id',
        ),
        migrations.AddField(
            model_name='hangmangame',
            name='game_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='hangmangame',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
