# Generated by Django 2.0 on 2020-05-28 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0008_auto_20200529_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='HangmanGame',
            fields=[
                ('game_id', models.AutoField(default='0', primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=20)),
                ('guessed', models.CharField(default='', max_length=10)),
                ('status', models.CharField(default='ongoing', max_length=10)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
