# Generated by Django 2.0 on 2020-05-28 23:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0009_hangmangame'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HangmanGame',
            new_name='Hangman_Game',
        ),
    ]
