# Generated by Django 2.0 on 2020-05-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_hangmangame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangmangame',
            name='game_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
