# Generated by Django 2.0 on 2020-05-28 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_hangmangame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hangmangame',
            name='user',
        ),
        migrations.DeleteModel(
            name='HangmanGame',
        ),
    ]
