# Generated by Django 2.0 on 2020-05-29 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0018_hangmangame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hangman',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=20)),
                ('guessed', models.CharField(default='', max_length=10)),
                ('status', models.CharField(default='ongoing', max_length=10)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='hangmangame',
            name='user',
        ),
        migrations.DeleteModel(
            name='HangmanGame',
        ),
    ]
