# Generated by Django 2.0 on 2020-05-31 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_auto_20200529_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangman',
            name='guessed',
            field=models.CharField(default='', max_length=27),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.CharField(choices=[['Fi fy Hunan', 'Fi fy Hunan'], ['Gwyliau', 'Gwyliau'], ['Ysgol', 'Ysgol'], ['Tywydd', 'Tywydd'], ['Amser', 'Amser'], ['Bwyd', 'Bwyd'], ['Ffasiwn', 'Ffasiwn'], ['Teulu a Ffrindiau', 'Teulu a Ffrindiau'], ['Trefn Ddyddiol', 'Trefn Ddyddiol'], ['Anifeiliad Anwes', 'Anifeiliad Anwes'], ['Cartref', 'Cartref'], ['Ardal', 'Ardal'], ['Hamdden a Hobiau', 'Hamdden a Hobiau'], ['Chwaraeon', 'Chwaraeon'], ['Digwyddiadau Arbennig', 'Digwyddiadau Arbennig'], ['Amser Gorffenol', 'Amser Gorffenol'], ['Cerddioraeth', 'Cerddioraeth'], ['Cymru, Digwylliant ac Enwogion', 'Cymru, Digwylliant ac Enwogion'], ["Cadw'n Iach", "Cadw'n Iach"], ['Y Penwythnos', 'Y Penwythnos'], ['Amser Dyfodol', 'Amser Dyfodol'], ['Gwaith', 'Gwaith'], ['Problemau Pobl Ifanc', 'Problemau Pobl Ifanc'], ['Y Amgylchedd', 'Y Amgylchedd'], ['Cyfryngau', 'Cyfryngau'], ['Technoleg', 'Technoleg']], max_length=50),
        ),
    ]
